image: maven:3-eclipse-temurin-17

definitions:
  steps:
    - step: &build-step
        name: SonarQube analysis
        caches:
          - maven
          - sonar
        script:
          - mvn clean verify sonar:sonar -Dsonar.projectKey=bitbucket-sonar-demo -Dsonar.projectName='bitbucket-sonar-demo' -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.token=${SONAR_TOKEN}
  caches:
    sonar: ~/.sonar

clone:
  depth: full
  
pipelines:
  branches:
    '{master}':
      - step: *build-step
